### ISSUE TITLE
Model does not exist returns undefined error

### ISSUE THREAD

**Issue by mathianasj** [jgretz/node-bits-sql#12]
If a model does not exist when executing any method, it should return an exception stating that the model does not exist

**Comment by mathianasj** [comment]
This may be something that should live in node-bits-internal-database

**Comment by jgretz** [comment]
Taken care of in node-bits-internal-database v0.0.7 with this commit: https://github.com/jgretz/node-bits-internal-database/commit/6b0da3c7bc20f46561ca5807bbb636003aa81888
